### ISSUE TITLE
Unable to reset and have storage filesystem readwrite

### ISSUE THREAD

**Issue by PaulskPt** [FoamyGuy/TR_Cowbell_Sequencer_Software#1]
Any idea how I can get the Circuitpython storage filesystem in readwrite mode? Last Friday I assembled the @DJDevon3's TR=COWBELL V1.2. Using also your TR_Cowbell_Sequencer_Software repo. According to all the documentation, I tried to get the CPY storage filesystem into readwrite mode to be able to write to the .json file. However the filesystem reports to be readonly after resetting the PicoW by pressing the <reset> button on the COWBELL board and simultaneously pressing the <BUTTON 1> (= UP button) of the 5 D-Pad buttons on the same board. It should work when the PicoW is not connected via USB, however it doesnt.

I tried various durations of pressing the <BUTTON 1>. I experienced that keeping on pressing this button, at or after the PicoW reset moment, inhibits the script to proceed, so I released the UP button.

See the images: [filesystem readonly](https://imgur.com/a/fezwLnk)

[filesystem readonly 2nd img](https://imgur.com/a/CysuI8h)

Here some REPL output while the PicoW on the TR=COWBELL was connected to my desktop PC via USB and running mu-editor.

> soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;🐍192.168.x.yy | code.py | 8.2.3\     (Note: IP-address masked)

TR=COWBELL test
board ID: "raspberry_pi_pico_w"
Storage filesystem is: Readonly
BUTTON 5 (MIDDLE) is pressed: True
new mode: selecting_note
BUTTON 5 (MIDDLE) is long pressed: True 
state.mode changed to: selecting_file
BUTTON 5 (MIDDLE) is long pressed: True   <<< NOTE: LONG PRESS
state.mode changed to: selecting_file
BUTTON 5 (MIDDLE) is pressed: True
saving
OSError while trying to save data to file. Error: [Errno 30] Read-only filesystem
BUTTON 5 (MIDDLE) is long pressed: True
state.mode changed to: selecting_file
BUTTON 5 (MIDDLE) is long pressed: True
state.mode changed to: selecting_file
BUTTON 5 (MIDDLE) is pressed: True
saving
OSError while trying to save data to file. Error: [Errno 30] Read-only filesystem
BUTTON 5 (MIDDLE) is pressed: True
saving
OSError while trying to save data to file. Error: [Errno 30] Read-only filesystem
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_file
loading: 0
BUTTON 5 (MIDDLE) is pressed: True
BUTTON 5 (MIDDLE) is pressed: True
new mode: selecting_note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
Key pressed : 0 / 0
setting led to: False
Key pressed : 0 / 1
setting led to: False
Key pressed : 0 / 2
setting led to: False
Key pressed : 0 / 5
setting led to: False
Key pressed : 0 / 7
setting led to: False
Key pressed : 1 / 3
setting led to: False
Key pressed : 1 / 4
setting led to: False
Key pressed : 1 / 5
setting led to: False
Key pressed : 0 / 0
setting led to: True
Key pressed : 0 / 2
setting led to: True
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
playing other channel? None
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
Key pressed : 0 / 0
setting led to: False
Key pressed : 0 / 0
setting led to: True
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
playing other channel? None
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
BUTTON 1 (UP) is pressed: True
BUTTON 1 (UP) state.mode: selecting_note
BUTTON 1 (up) increasing note
0 -> 1
1 -> 2
2 -> 3
3 -> 1
1 -> -7
-7 -> -12
-12 -> -13
-13 -> -14
-14 -> -15
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note
BUTTON 3 (DOWN) is pressed: True
BUTTON 3 (DOWN) state.mode: selecting_note
BUTTON 3 (DOWN) decreasing note

By the way: in file code_pico.py, function read_buttons(), if middle_btn.fell: ,
I added a 2nd try...except block to not have the script crash when it tries to write to a filesystem that is readonly.
See image: [added try...except block](https://imgur.com/a/Rp60NAZ)

**Comment by PaulskPt** [comment]
Probably I should create this issue with the CPY team (CPY repo).

**Comment by FoamyGuy** [comment]
@PaulskPt do you have the accompanying boot.py file on your drive? 

This learn guide details the read / write restrictions and the default behavior on CircuitPython: https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage basically only 1 "thing" can have write mode access at a time, either CircuitPython code, or the PC connected via USB. The `boot.py` file can contain code that makes a selection of which one will have write access.

For this project I used this file: https://github.com/FoamyGuy/TR_Cowbell_Sequencer_Software/blob/main/boot_pico.py to check a specific button's value and then set the writeable mode based on it's value, that way the button then controls which thing will have write access.

The file does need to be renamed to specifically `boot.py` and placed in the root of the CIRCUITPY drive in order to work.

**Comment by PaulskPt** [comment]
Thank you! Solved: yes, I had the boot_pico.py on the drive but forgot the rename it to boot.py.
Now I managed to switch between RO and RW. I experienced that after a reset + up-button sequence I had to reset another time to see in the opening message that the filesystem was in "Writeble" mode. Issue closed!
